;	Based on Mowasai by Ian Klimon


[GeneralSettings]
name			= LB Jupiter
description		= Jupiter is a defensive Nationalist general who focuses on building holy armies to combat darkness.
skill_level		= 2	; 0 = Easy | 1 = Medium | 2 = Hard
preferredfaction	= NATIONALIST
full_recompute_time	= 18.0	; seconds per full recompute of strategy (float)
sai_wait_threshold	= 6.0	;
early_game_threshold	= 2	;
early_game_full_recompute_time 	= 15.0;

[GoalPriorityList]
explore			=  70.0	; priority to go to unexlored regions (float)
distance		= -15.0 ; reduced priority according to region distance (float)
combat			=  35.0	; enemy combat priority (float)
building_defend		=  95.0	; friendly building defense priority (float)
building_attack		=  30.0	; enemy building attack priority (float)
repair			=  99.0	; repair damaged friendly buildings, set to zero if not to be used (float)
guard			=  70.0	; guard regions  (at border or near my towns) (float)
reinforce		= 120.0	; move injured units to friendly supply zone(float)
build_city		=  90.0 ;
build_outpost		=  95.0	; new outpost priority (float)
build_mine		=  60.0	; priority to build a new mine (float)
build_structure		=  65.0	; building a new structure in a city (float)
upgrade_structure	=  45.0	; upgrade an existing structure in a city (float)
commission_unit		=  55.0	; commissioning a new unit (float)


[GoalPriorityBonus]
fuzziness			=  5.0	; max fuzzy priority--fuzzy priority will be in a range from 0 to this  (float)
destroy_captured_base_percent	=  0.75	; percent to raze a building surrounded by enemy.  (float)
percent_engage_captain		=  0.80	; % chance the captain will be set to engage rather than command (float)
wake_hero_threshold     	=    35	; [1.0.11] minimum gold income before will awaken heroes (float)
percent_borrow_for_upgrade 	=  0.40	; [1.2.0] chance of upgrading on whim by stealing from other accounts


[MaxEvalGoals]
explore			= 6
attack			= 2
guard			= 6	; how many patrol/perimeter/guard goals per settlement  (char)
construct		= 3	; how many new buildings goals (new cities, outposts, mines) per settlement  (char)
upgrade			= 6	; how many new structure goals (city upgrades) per settlement  (char)


[MaxExecGoals]
explore 		= 3
attack			= 2
guard			= 5	; how many patrol/perimeter/guar goals per settlement  (char)
construct		= 2	; how many new buildings goals (new cities, outposts, mines) per settlement  (char)
upgrade			= 5	; how many new structure goals (city upgrades) (char)


[StrengthRatios]
matching_ratio_min	=   1.1	; Minimum force strength ratio when engaging enemy  (float)
matching_ratio_max	=   8.0	; Maximum  (float)
building_bonus_min	=   0.0	; Minimum force strength bonus per building when present (float)
building_bonus_max	=   5.0	; Maximum, note this is both for friendly (on defense) as well as enemy (on attack) when there are enemy present (float)
explore_min		=  25.0 ;
explore_max		=  75.0	; Maximum (float) --These are counted Before a unit is added, so only one unit will be added to each
guard_min		=  5.0	; Minimum force strength to be guarding areas (borders or near my cities) (float)
guard_max		=  75.0	; Maximum (float)


[GoldRatio]
build			=  0.15	; % of resources will go toward building and upgrading settlements and other stand-alone structures(float)
upgrade			=  0.50	; % of resources will go toward building new settlement structures, like sawmills(float)
unit			=  0.35	; % of resources will go toward commissioning new companies(float)


[StructurePriorityList]
Woodmill		=   16.0 ;
Blacksmith		=   10.5 ;
Barracks                =   10.0 ; priority to build a Barracks (float)
Temple                  =   10.0 ; priority to build a Temple (float)
Library			=    4.0
Wall			=    8.0
Market			=   12.0
Quarry			=    8.0 ;


[StructureUpgradePriorityList]
MiningPost              =  10.0 ; priority to upgrade a Quarry to a Mining Post (float)
MasonryGuild            =   0.0 ; priority to upgrade a Quarry to a Masonry Guild (float)
StoneMarket             =   0.0 ; priority to upgrade a Quarry to a Stone Export (float)
Sawmill                 =   0.0 ; priority to upgrade a Woodmill to a Sawmill (float)
CarpentryGuild          =  16.0 ; priority to upgrade a Woodmill to a Carpentry Guild (float)
WoodMarket              =   0.0 ; priority to upgrade a Woodmill to a Wood Export (float)
BlastFurnace            =   4.0 ; priority to upgrade a Blacksmith to a Blast Furnace (float)
ArmoryGuild             =   6.0 ; priority to upgrade a Blacksmith to an Armory Guild [Except Ceyah] (float)
ManaForge               =  12.0 ; priority to upgrade a Blacksmith to a Mana Forge [Ceyah] (float)
IronMarket              =   0.0 ; priority to upgrade a Blacksmith to an Iron Export (float)
Bazaar                  =   0.0	; priority to upgrade a Market to a Bazaar (float)
Bank                    =  12.0 ; priority to upgrade a Market to a Bank (float)
Factory                 =   7.0 ; priority to upgrade a Market to a Factory [Nationalist] (float)
Workshop                =  10.0	; priority to upgrade a Market to a Workshop [Royalist] (float)
Billet                  =   6.0 ; priority to upgrade a Barracks to a Billet [Royalist] (float)
Garrison                =   2.0 ; priority to upgrade a Barracks to a Garrison (float)
SupplyPost              =  10.0 ; priority to upgrade a Barracks to a Supply Post (float)
TempleOfTheOverseers    =   8.0 ; priority to upgrade a Temple to Light of Faith [Council] (float)
WayOfImmortality        =   8.0 ; priority to upgrade a Temple to Eternal Path [Royalist] (float)
Nightbringers           =   8.0 ; priority to upgrade a Temple to Nightbringer [Nationalist] (float)
Nightbringers2          =   8.0 ; priority to upgrade a Temple to Nightbringer [Ceyah] (float)
MageCollege             =  12.0 ; priority to upgrade a Library to a Mage College (float)
AstrologyHall           =  10.0 ; priority to upgrade a Library to an Astrology Hall (float)
WizardTower             =   8.0 ; priority to upgrade a Library to a Wizard Tower [Council] (float)
WatchTowers             =   0.0 ; priority to upgrade a Wall to Watch Towers (float)
FortifiedWall           =  10.0 ; priority to upgrade a Wall to Fortified Wall (float)
TurretedRamparts        =   6.0 ; priority to upgrade a Wall to Turreted Ramparts [Ceyah] (float)


[StructurePriorityBonus]
fuzziness		=   4.0	; structure priority fuzziness (float)
target_upgrade_ratio	=  0.65 ; Target percent of upgraded structures to non-upgraded structures


[CompanyFrontPriorityList]
ARCHER                  =   4.0 ; [Except Ceyah] (float)
CAVALIER		=   6.0 ;
DRAGOON                 =   8.0 ; [Except Ceyah] (float)
DRAUGA_BEASTRIDER       =   0.0 ; [Drauga] (float)
DRAUGA_BERSERKER        =   0.0 ; [Drauga] (float)
FOOTMAN                 =   8.0 ; [Except Ceyah] (float)
GAURI_ANVIL             =  16.0 ; [Gauri] (float)
GAURI_HAMMER            =   8.0 ; [Gauri] (float)
GOLEM                   =   8.0 ; [Tech - All] (float)
GRENADIER               =  32.0	; [Except Ceyah] (float)
HAROUN_ARCHER           =   0.0 ; (Rainbringer) [Haroun] (float)
INFANTRY                =  20.0	; [Except Ceyah] (float)
REAVER                  =   0.0 ; (Bone Reaver) [Tech (Ceyah)] (float)
RHAKSHA_SLAVE           =   0.0 ; [Tech (Ceyah)] (float)
SCOUT                   =   2.0	; [Except Ceyah] (float)
SHADELING_SCOUT         =   0.0	; (Shadeling) [Ceyah] (float)
SHADOW_BEAST            =   0.0 ; [Ceyah] (float)
SHOCK_TROOPER           =  32.0	; (Elite Guard) [Nationalist Elite] (float)
WINDRIDER               =   0.0 ; [Haroun] (float)
ZOMBIE                  =-100.0	; [Ceyah] (float)
VOID_BEAST		=   0.0
UNDEAD_ARCHER		=   0.0
SKELETON		=   0.0
RHAKSHA_HUNTER		=   0.0
ELITE_ARCHER		=   4.0
ENGINEER		=  14.0
;	Ahriman's Gift Front-Line Units
COMBAT_ENGINEER		=  20.0
LANCER			=   6.0
MERCENARY		=   4.0
PIONEER			=  32.0
CROSSBOWMAN             =   8.0	; [Council] (float)
DISCIPLE                =  24.0 ; [Nationalist] (float)
HORSE_ARCHER            =   0.0 ; [Royalist] (float)
SHADOW_KNIGHT           =   0.0 ; [Ceyah] (float)
SLAANRI_CHAMPION	=   0.0 ; [Tech - All] (float)
SLAANRI_WARRIOR         =   0.0 ; [Slaanri] (float)
;	LB Front-Line Units
CATAPHRACT		=  4.0 ;
CULTIST			=  0.0 ;
GHOST			=  0.0 ;
HUSSAR			=  2.0 ;
ARCHERC			=  8.0 ; Man at Arms
ENGINEER_MINER		=  6.0 ; Miner
SHADOW_BEAST2		=  0.0 ; Night Beast
GOLEM2			= 10.0 ; Golem Warrior
PIKEMAN			= 12.0 ;
KNIGHT			= 25.0 ;
PIKEMANSUPER		= 5.0 ;


[CompanySupportPriorityList]
ARCHMAGE                =   4.0	; [Tech - All] (float)
AVATAR                  =  32.0	; [Tech - Except Ceyah] (float)
BATTLE_PRIEST           =  20.0 ; [Royalist] (float)
CHANNELER               =  20.0 ; [Council] (float)
CLERIC                  =  18.0	; [Except Ceyah] (float)
CONJUROR                =   6.0 ; [Tech - All] (float)
DEVOUT                  =   0.0 ; [Tech - Ceyah] (float)
DREADLORD               =   0.0 ; [Ceyah] (float)
ENCHANTER               =   0.0	; [Tech - All] (float)
LICH                    =   0.0 ; [Tech - Ceyah] (float)
NECROMANCER             =   0.0 ; [Ceyah] (float)
PALADIN                 =  28.0	; [Except Ceyah] (float)
PATHFINDER              =   8.0 ; [Tech - Except Ceyah] (float)
PROPHET                 =   0.0 ; [Ceyah] (float)
RANGER                  =   6.0 ; [Except Ceyah] (float)
SHADOW_DEMON            =   0.0 ; [Ceyah] (float)
SHADOW_PRIEST           =   0.0 ; [Ceyah] (float)
SORCERESS               =   0.0 ; [Royalist] (float)
SUMMONER                =   6.0 ; [Nationalist] (float)
WARLOCK                 =   4.0 ; [Tech - All] (float)
WARMAGE                 =   4.0 ; (Magician) [Except Ceyah] (float)
WIZARD                  =   4.0 ; [Council] (float)
WRAITH                  =   0.0 ; [Ceyah] (float)
ZEALOT                  =  20.0 ; [Nationalist] (float)
;	Ahriman's Gift Support Units
DEFILER                 =   0.0	; [Tech - Ceyah] (float)
FANATIC                 =  10.0	; [Nationalist Elite Priest] (float)
INVOKER                 =   6.0 ; [Nationalist Elite Mage] (float)
KHALDUNITE_GOLEM	=   6.0 ; [Tech - All] (float)
MAELSTROM_ORB           =   8.0 ; [Except Ceyah] (float)
SHADOW_PROPHET          =   0.0 ; [Tech - Ceyah] (float)
SLAANRI_MYSTIC          =  24.0 ; [Slaanri] (float)
SLAANRI_SLAVER		=   0.0 ; [Tech - All] (float)
ORACLE			=  20.0 ;
MACABRE			=   0.0 ;
SORCEROR		=   4.0 ;
STORM_LORD		=   4.0 ;
ACOLYTE			=   0.0 ;
ELEMENTALIST		=   4.0 ;
HIGH_PRIEST		=  30.0 ;
;	LB units
CROSSBOWMAN2		=   8.0 ;
MAELSTROM_ORB2		=  12.0 ;
DREAD_KNIGHT		=   0.0 ;
ARCHER_SUPPORT		=   4.0 ;
DISCIPLEMONK		=  20.0 ;
SHADELING_SUPPORT	=   0.0 ;
TARKAN			=   4.0 ;
OVERSEER		=  12.0 ;
LICHSUPER		=   0.0;




[CompanySupportChoiceRatio]
support			=  1.00	; use specialty support units (mages, paladins, whatever) (float)
complementary		=  0.00	; archers with melee or melee with archers; complementary also picks up when support units aren't available (float)
homogenous		=  0.00	; support unit matching the front line ones (float)
none			=  0.00	; only use the front line units, no support (float)


[CompanySupportPriorityBonus]
percent_big_engineer	=  0.50	; percent of engineer companies that have 6 versus only 4 engineer units (float)
percent_mixed_engineer	=  0.75	; percent an engineer company will have different support units
matching_support	=  -15.0; extra priority for the 2nd support unit matching the first (for special support units only) (float)
fuzziness		=   5.0	; fuzzy range for support units (float)


[PoliticalTendencies]
aloof			=   0.01; (0.0-0.5) % push opinion towards 0(neutral) each think turn
levelheaded		=  -0.1 ;
chaotic			=   0.02; (0.0-0.5) random shift of opinion on each think turn. 0.5 would result in a random shift from -25% to +25%
loyal			=   0.5	; (0.0-0.5) For all ALLIES, % increase for good events & % reduction of bad events
vindictive		=   0.5	; (0.0-0.5) For all ENEMIES, % reduction for good events & % increase of bad events
suspicious		=   0.5	; (0.0-0.5) For all players, % reduction for good events & % increase of bad events
greedy			=  -1.0 ;


[PoliticalTreatyOfferThreshold]
DeclareWar		=  -5.0	; If opinion falls below this point, the player will delare war
OfferPeace		=  35.0	; Offer a peace treaty
CancelAlliance		=  45.0	; Cancel an alliance
OfferAlliance		=  95.0	; Offer an alliance


[PoliticalTreatyAcceptThreshold]
OfferPeace		=  15.0	; Accept an offered peace treaty
OfferAlliance		=  75.0 ;


[BuildTemplates]
Template1	= EarlyMili
Template2	= MidMili
Template3	= EliteMili
Template4	= EarlyEcon
Template5	= MidEcon
Template6	= LateEcon
Template7 	= HarounSanctuary
Template8 	= DraugaEnclave
Template9 	= GauriStronghold
Template10 	= SlaanriKraal
Template11	= CeyahMili
Template12	= RoyalistMili


[EarlyMili]
Component1 	= CarpentryGuild
Component2 	= SupplyPost
MinEconomy 	= 35		; default -infinity
OnlyFaction 	= NATIONALIST	; default NONE
Bonus 		= 500		; default 50


[MidMili]
Component1 	= CarpentryGuild
Component2 	= BlastFurnace
Component3 	= Temple
Component4 	= SupplyPost
MinEconomy 	= 75		; default -infinity
OnlyFaction 	= NATIONALIST	; default NONE
Bonus 		= 1000		; default 50


[EliteMili]
Component1 	= CarpentryGuild
Component2 	= ArmoryGuild
Component3 	= Nightbringers
Component4 	= SupplyPost
Component5	= AstrologyHall
MinEconomy 	= 105		; default -infinity
OnlyFaction 	= NATIONALIST	; default NONE
Bonus 		= 1000		; default 50


[EarlyEcon]
Component1 	= CarpentryGuild
Component2 	= Bank
MaxInstances 	= 3		; default 1
OnlyFaction 	= NATIONALIST	; default NONE


[MidEcon]
Component1 	= Bank
Component2 	= BlastFurnace
MaxInstances 	= 2		; default 1
MinEconomy 	= 55		; default -infinity
OnlyFaction 	= NATIONALIST	; default NONE


[LateEcon]
Component1 	= BlastFurnace
Component2 	= Temple
MaxInstances 	= 4		; default 1
MinEconomy 	= 75		; default -infinity
OnlyFaction 	= NATIONALIST	; default NONE


[HarounSanctuary]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3 	= Library
Component4	= Bank
Race 		= HAROUN	; default ANY
Bonus 		= 500		; default 50


[DraugaEnclave]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3 	= Library
Component4	= Bank
Race 		= DRAUGA	; default ANY
Bonus 		= 500		; default 50


[GauriStronghold]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3 	= Library
Component4	= Bank
Race 		= GAURI		; default ANY
Bonus 		= 500		; default 50


[SlaanriKraal]
Component1 	= Quarry
Component2 	= Temple
Race 		= SLAAN		; default ANY
Bonus 		= 500		; default 50


[CeyahMili]
Component1 	= CarpentryGuild
Component2 	= Library
Component3 	= ManaForge
MinEconomy 	= 25		; default -infinity
OnlyFaction 	= CEYAH		; default ANY
Bonus 		= 500		; default 50


[RoyalistMili]
Component1 	= CarpentryGuild
Component2	= BlastFurnace
Component3	= Barracks
Component4 	= Library
Component5 	= Workshop
MinEconomy 	= 25		; default -infinity
OnlyFaction 	= ROYALIST	; default ANY
Bonus 		= 500		; default 50


