;	Based on Andrae SAI by Ian Klimon

[GeneralSettings]
name                    = LB Oceanus
description             = Oceanus (LB Ceyah) favours large armies of cultists until he gets his iron economy up and running.
skill_level             = 1	; 0 = Easy | 1 = Medium | 2 = Hard
preferredfaction        = CEYAH
full_recompute_time	= 20.0  ;


[GoalPriorityList]
distance		=  0.0	; reduced priority according to region distance (float)
reinforce               = 100.0 ; move injured units to friendly supply zone (float)
build_mine              =  75.0	; priority to build a new mine (float)
build_city		= 100.0 ;
build_outpost		=   5.0 ;
build_structure         =  45.0	; building a new structure in a city (float)
upgrade_structure       =  25.0	; upgrade an existing structure in a city (float)
commission_unit         =  90.0	; commissioning a new unit (float)
explore			=  55.0 ; urge to go to unexplored regions
combat 			=  40.0 ;
building_attack		=  55.0 ; urge to attack enemy buildings
building_defend		=  20.0 ;
guard			=  20.0 ; urge to defend regions


[GoalPriorityBonus]
wake_hero_threshold     	=    35	; [1.0.11] minimum gold income before will awaken heroes (float)
percent_borrow_for_upgrade 	=   0.0	; [1.2.0] chance of upgrading on whim by stealing from other accounts
percent_engage_captain		=   1.0 ;



[MaxEvalGoals]
explore			= 4
attack			= 4
guard			= 1	; how many patrol/perimeter/guard goals per settlement  (char)
construct		= 3	; how many new buildings goals (new cities, outposts, mines) per settlement  (char)
upgrade			= 2	; how many new structure goals (city upgrades) per settlement  (char)


[MaxExecGoals]
explore 		= 3
attack			= 3
guard			= 1	; how many patrol/perimeter/guar goals per settlement  (char)
construct		= 2	; how many new buildings goals (new cities, outposts, mines) per settlement  (char)
upgrade			= 1	; how many new structure goals (city upgrades) (char)

[StrengthRatios]
matching_ratio_min      =   3.0	; Minimum force strength ratio when engaging enemy (float)
matching_ratio_max      =   8.0	; Maximum (float)


[GoldRatio]
build                   =  0.25	; % of resources will go toward building and upgrading settlements and other stand-alone structures (float)
upgrade                 =  0.20	; % of resources will go toward building new settlement structures, like sawmills (float)
unit                    =  0.55	; % of resources will go toward commissioning new companies (float)


[StructurePriorityList]
Quarry			= 100.0 ; priority to build a Quarry (float)
Blacksmith		=  75.0 ; priority to build a Blacksmith
Temple                  =  65.0	; priority to build a Temple (float)
Barracks                =  50.0	; priority to build a Barracks (float)
Woodmill		=  50.0 ;
Wall                    =-100.0	; priority to build a Wall (float)


[StructureUpgradePriorityList]
MiningPost		= 100.0 ; priority to upgrade to mining post (float)
MasonryGuild		=  10.0 ;
StoneMarket		=   1.0 ;
SupplyPost		=  75.0 ;
Nightbringers2		=  25.0 ;
BlastFurnace		=  50.0 ;
WoodMarket		= 100.0 ;


[CompanyFrontPriorityList]
CULTIST			=  55.0 ; [Ceyah] (float)
SHADELING_SCOUT         =-100.0	; (Shadeling) [Ceyah] (float)
SHADOW_BEAST            =   5.0	; [Ceyah] (float)
SHADOW_KNIGHT           =  10.0	; [Ceyah] (float)
SKELETON                =  15.0	; [Ceyah] (float)
UNDEAD_ARCHER           =  15.0	; (Bone Bow) [Ceyah] (float)
VOID_BEAST              =   5.0	; [Ceyah Elite] (float)
ZOMBIE                  =  25.0	; [Ceyah] (float)
GHOST			=  35.0 ;
SHADOW_DEMONFRONT	=  35.0 ;
SETTLER			=  80.0 ;
ENGINEER		=  40.0 ;
PIKEMANSUPER		=  1.0  ;



[CompanySupportPriorityList]
ACOLYTE                 =  24.0 ; [Tech - Ceyah] (float)
DEFILER                 =  20.0 ; [Tech - Ceyah] (float)
DEVOUT                  =  20.0 ; [Tech - Ceyah] (float)
DREADLORD               =  16.0 ; [Ceyah] (float)
LICH                    =  20.0 ; [Tech - Ceyah] (float)
MACABRE                 =  24.0 ; [Tech - Ceyah] (float)
NECROMANCER             =  12.0 ; [Ceyah] (float)
PROPHET                 =  16.0 ; [Ceyah] (float)
SHADOW_DEMON            =   8.0 ; [Ceyah] (float)
SHADOW_PRIEST           =  24.0 ; [Ceyah] (float)
SHADOW_PROPHET          =  24.0 ; [Tech - Ceyah] (float)
SLAANRI_SLAVER          =  16.0 ; [Tech - All] (float)
WRAITH                  =  16.0 ; [Ceyah] (float)
SHADELING_SUPPORT	=  33.0 ; [Ceyah] (float)
LICHSUPER		=  50.0 ;


[CompanySupportChoiceRatio]
support			=  0.50	; use specialty support units (mages, paladins, whatever) (float)
homogenous		=  0.50	; support unit matching the front line ones (float)

[CompanySupportPriorityBonus]
percent_big_engineer    =  0.00	; percent of engineer companies that have 6 versus only 4 engineer units (float)


[PoliticalTendencies]
aloof                   =   0.0	; (0.0-0.5) % push opinion towards 0 (neutral) each think turn
chaotic                 =   0.5 ; (0.0-0.5) random shift of opinion on each think turn. 0.5 would result in a random shift from -25% to +25%
vindictive              =   0.5 ; (0.0-0.5) For all ENEMIES, % reduction for good events & % increase of bad events
suspicious              =   0.5 ; (0.0-0.5) For all players, % reduction for good events & % increase of bad events
greedy                  =   1.0 ; (-1.0-1.0) For all players, % increase(decrease) in opinion effects from tribute


[PoliticalTreatyOfferThreshold]
DeclareWar              =  -5.0	; If opinion falls below this point, the player will delare war


[BuildTemplates]
Template1 	= EarlyMili
Template2 	= MidMili
Template3	= EliteMili
Template4 	= EarlyEcon
Template5 	= MidEcon
Template6 	= LateEcon
Template7 	= HarounSanctuary
Template8 	= DraugaEnclave
Template9 	= GauriStronghold
Template10 	= SlaanriKraal
Template11	= RoyalMili
Template12	= MaretenMili


[EarlyMili]
Component1 	= WoodMarket
Component2 	= MiningPost
Component3 	= Nightbringers2
MinEconomy 	= 20		; default -infinity
OnlyFaction 	= CEYAH		; default ANY
Bonus 		= 500		; default 50


[MidMili]
Component1 	= WoodMarket
Component2	= MiningPost
Component3	= SupplyPost
Component4 	= BlastFurnace
Component5 	= Nightbringers2
MinEconomy 	= 40		; default -infinity
OnlyFaction 	= CEYAH		; default ANY
Bonus 		= 500		; default 50


[EliteMili]
Component1 	= WoodMarket
Component2 	= MiningPost
Component3 	= BlastFurnace
Component4 	= Nightbringers2
Component5 	= SupplyPost
MinEconomy 	= 105		; default -infinity
OnlyFaction 	= CEYAH		; default ANY
Bonus 		= 1000		; default 50


[EarlyEcon]
Component1 	= MiningPost
Component2 	= IronMarket
Component3 	= WoodMarket
MaxInstances 	= 2		; default 1
Race 		= MARETEN	; default ANY


[MidEcon]
Component1 	= MiningPost
Component2 	= Blacksmith
Component3 	= WoodMarket
MaxInstances 	= 2		; default 1
MinEconomy 	= 60		; default -infinity
Race 		= MARETEN	; default ANY


[LateEcon]
Component1 	= MiningPost
Component2 	= Blacksmith
Component3 	= Library
MaxInstances 	= 2		; default 1
MinEconomy 	= 85		; default -infinity
Race 		= MARETEN	; default ANY


[HarounSanctuary]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3 	= Library
Component4	= Bank
Race 		= HAROUN	; default ANY
Bonus 		= 500		; default 50


[DraugaEnclave]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3 	= Library
Component4	= Bank
Race 		= DRAUGA	; default ANY
Bonus 		= 500		; default 50


[GauriStronghold]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3 	= Library
Component4	= Bank
Race 		= GAURI		; default ANY
Bonus 		= 500		; default 50


[SlaanriKraal]
Component1 	= Quarry
Component2 	= Temple
Race 		= SLAAN		; default ANY
Bonus 		= 500		; default 50


[RoyalMili]
Component1	= CarpentryGuild
Component2 	= ArmoryGuild
Component3 	= Library
Component4	= Barracks
Component5	= Workshop
MinEconomy 	= 25		; default -infinity
OnlyFaction 	= ROYALIST	; default ANY
Bonus 		= 500		; default 50


[MaretenMili]
Component1	= CarpentryGuild
Component2 	= ArmoryGuild
Component3 	= Library
Component4	= Bank
MinEconomy 	= 25		; default -infinity
ExceptFaction 	= CEYAH		; default ANY
Race 		= MARETEN	; default ANY

