;	Based on Andrae SAI by Ian Klimon

[GeneralSettings]
name                    = LB Pluto
description             = Pluto is a cunning Ceyah general with a ghastly army and calculated ambition.
skill_level             = 2	; 0 = Easy | 1 = Medium | 2 = Hard
preferredfaction        = CEYAH
full_recompute_time	= 20.0  ;
early_game_full_recompute_time = 20.0 ;
early_game_threshold 	= 4 ;


[GoalPriorityList]
distance		=  -8.0	; reduced priority according to region distance (float)
reinforce               = 110.0 ; move injured units to friendly supply zone (float)
build_mine              =  75.0	; priority to build a new mine (float)
build_city		= 115.0 ;
build_structure         =  35.0	; building a new structure in a city (float)
build_outpost		=  65.0 ;
upgrade_structure       =  45.0	; upgrade an existing structure in a city (float)
commission_unit         =  70.0	; commissioning a new unit (float)
explore			=  45.0 ; urge to go to unexplored regions
combat 			=  30.0 ;
building_attack		=  35.0 ; urge to attack enemy buildings
building_defend		=  75.0 ;
guard			=  60.0 ; urge to defend regions


[GoalPriorityBonus]
percent_engage_captain		=   0.30;
wake_hero_threshold     	=    35	; [1.0.11] minimum gold income before will awaken heroes (float)
percent_borrow_for_upgrade 	=   0.20; [1.2.0] chance of upgrading on whim by stealing from other accounts


[MaxEvalGoals]
explore			= 4
attack			= 5
guard			= 3	; how many patrol/perimeter/guard goals per settlement  (char)
construct		= 3	; how many new buildings goals (new cities, outposts, mines) per settlement  (char)
upgrade			= 4	; how many new structure goals (city upgrades) per settlement  (char)


[MaxExecGoals]
explore 		= 3
attack			= 2
guard			= 2	; how many patrol/perimeter/guar goals per settlement  (char)
construct		= 2	; how many new buildings goals (new cities, outposts, mines) per settlement  (char)
upgrade			= 2	; how many new structure goals (city upgrades) (char)


[StrengthRatios]
matching_ratio_min      =   2.0	; Minimum force strength ratio when engaging enemy (float)
matching_ratio_max      =   7.0	; Maximum (float)


[GoldRatio]
build                   =  0.35	; % of resources will go toward building and upgrading settlements and other stand-alone structures (float)
upgrade                 =  0.35	; % of resources will go toward building new settlement structures, like sawmills (float)
unit                    =  0.30	; % of resources will go toward commissioning new companies (float)


[StructurePriorityList]
Woodmill		=   16.0 ;
Blacksmith		=   12.0 ;
Barracks                =   10.0 ; priority to build a Barracks (float)
Temple                  =   5.0 ; priority to build a Temple (float)
Library			=    9.0
Wall			=    8.0
Market			=   12.0
Quarry			=   12.0 ;


[StructureUpgradePriorityList]
MiningPost              =  10.0 ; priority to upgrade a Quarry to a Mining Post (float)
MasonryGuild            =   0.0 ; priority to upgrade a Quarry to a Masonry Guild (float)
StoneMarket             =   0.0 ; priority to upgrade a Quarry to a Stone Export (float)
Sawmill                 =   0.0 ; priority to upgrade a Woodmill to a Sawmill (float)
CarpentryGuild          =  16.0 ; priority to upgrade a Woodmill to a Carpentry Guild (float)
WoodMarket              =   0.0 ; priority to upgrade a Woodmill to a Wood Export (float)
BlastFurnace            =   4.0 ; priority to upgrade a Blacksmith to a Blast Furnace (float)
ArmoryGuild             =   0.0 ; priority to upgrade a Blacksmith to an Armory Guild [Except Ceyah] (float)
ManaForge               =  12.0 ; priority to upgrade a Blacksmith to a Mana Forge [Ceyah] (float)
IronMarket              =   0.0 ; priority to upgrade a Blacksmith to an Iron Export (float)
Bazaar                  =   0.0	; priority to upgrade a Market to a Bazaar (float)
Bank                    =  12.0 ; priority to upgrade a Market to a Bank (float)
Factory                 =   7.0 ; priority to upgrade a Market to a Factory [Nationalist] (float)
Workshop                =  10.0	; priority to upgrade a Market to a Workshop [Royalist] (float)
Billet                  =   6.0 ; priority to upgrade a Barracks to a Billet [Royalist] (float)
Garrison                =   2.0 ; priority to upgrade a Barracks to a Garrison (float)
SupplyPost              =  10.0 ; priority to upgrade a Barracks to a Supply Post (float)
TempleOfTheOverseers    =   8.0 ; priority to upgrade a Temple to Light of Faith [Council] (float)
WayOfImmortality        =   8.0 ; priority to upgrade a Temple to Eternal Path [Royalist] (float)
Nightbringers           =   8.0 ; priority to upgrade a Temple to Nightbringer [Nationalist] (float)
Nightbringers2          =   8.0 ; priority to upgrade a Temple to Nightbringer [Ceyah] (float)
MageCollege             =  12.0 ; priority to upgrade a Library to a Mage College (float)
AstrologyHall           =   4.0 ; priority to upgrade a Library to an Astrology Hall (float)
WizardTower             =   8.0 ; priority to upgrade a Library to a Wizard Tower [Council] (float)
WatchTowers             =   4.0 ; priority to upgrade a Wall to Watch Towers (float)
FortifiedWall           =   4.0 ; priority to upgrade a Wall to Fortified Wall (float)
TurretedRamparts        =   9.0 ; priority to upgrade a Wall to Turreted Ramparts [Ceyah] (float)


[CompanyFrontPriorityList]
ARCHER                  =   4.0 ; [Except Ceyah] (float)
CAVALIER		=   0.0 ;
DRAGOON                 =   0.0 ; [Except Ceyah] (float)
DRAUGA_BEASTRIDER       =   8.0 ; [Drauga] (float)
DRAUGA_BERSERKER        =   8.0 ; [Drauga] (float)
FOOTMAN                 =   4.0 ; [Except Ceyah] (float)
GAURI_ANVIL             =   8.0 ; [Gauri] (float)
GAURI_HAMMER            =   8.0 ; [Gauri] (float)
GOLEM                   =   8.0 ; [Tech - All] (float)
GRENADIER               =   4.0	; [Except Ceyah] (float)
HAROUN_ARCHER           =   4.0 ; (Rainbringer) [Haroun] (float)
INFANTRY                =   4.0	; [Except Ceyah] (float)
REAVER                  =  20.0 ; (Bone Reaver) [Tech (Ceyah)] (float)
SCOUT                   =   2.0	; [Except Ceyah] (float)
SHADELING_SCOUT         =   8.0	; (Shadeling) [Ceyah] (float)
SHADOW_BEAST            =  26.0 ; [Ceyah] (float)
SHOCK_TROOPER           =   2.0	; (Elite Guard) [Nationalist Elite] (float)
WINDRIDER               =   2.0 ; [Haroun] (float)
ZOMBIE                  =   6.0	; [Ceyah] (float)
VOID_BEAST		=  32.0
UNDEAD_ARCHER		=  12.0
SKELETON		=  13.0
RHAKSHA_HUNTER		=  32.0
RHAKSHA_SLAVE		=  16.0
ELITE_ARCHER		=   4.0
ENGINEER		=  20.0
SETTLER			=  60.0
;	Ahriman's Gift Front-Line Units
COMBAT_ENGINEER		=  12.0
LANCER			=   2.0
MERCENARY		=  16.0
PIONEER			=  32.0
CROSSBOWMAN             =   4.0	; [Council] (float)
DISCIPLE                =   0.0 ; [Nationalist] (float)
HORSE_ARCHER            =   0.0 ; [Royalist] (float)
SHADOW_KNIGHT           =  24.0 ; [Ceyah] (float)
SLAANRI_CHAMPION	=   0.0 ; [Tech - All] (float)
SLAANRI_WARRIOR         =   0.0 ; [Slaanri] (float)
;	LB Front-Line Units
CATAPHRACT		=  4.0 ;
CULTIST			=  8.0 ;
GHOST			= 20.0 ;
HUSSAR			=  2.0 ;
ARCHERC			=  2.0 ; Man at Arms
ENGINEER_MINER		=  2.0 ; Miner
SHADOW_BEAST2		= 18.0 ; Night Beast
GOLEM2			=  8.0 ; Golem Warrior
PIKEMAN			=  2.0 ;
SHADOW_DEMONFRONT	= 16.0 ;
PIKEMANSUPER		=  3.0 ;
NYMPH			= 0.0 ; Nymph


[CompanySupportPriorityList]
ARCHMAGE                =   2.0	; [Tech - All] (float)
AVATAR                  =   0.0	; [Tech - Except Ceyah] (float)
BATTLE_PRIEST           =   2.0 ; [Royalist] (float)
CHANNELER               =   0.0 ; [Council] (float)
CLERIC                  =   0.0	; [Except Ceyah] (float)
CONJUROR                =  16.0 ; [Tech - All] (float)
DEVOUT                  =  10.0 ; [Tech - Ceyah] (float)
DREADLORD               =  17.0 ; [Ceyah] (float)
ENCHANTER               =   6.0	; [Tech - All] (float)
LICH                    =  16.0 ; [Tech - Ceyah] (float)
NECROMANCER             =  22.0 ; [Ceyah] (float)
PALADIN                 =   0.0	; [Except Ceyah] (float)
PATHFINDER              =   8.0 ; [Tech - Except Ceyah] (float)
PROPHET                 =   8.0 ; [Ceyah] (float)
RANGER                  =   6.0 ; [Except Ceyah] (float)
SHADOW_DEMON            =  12.0 ; [Ceyah] (float)
SHADOW_PRIEST           =   8.0 ; [Ceyah] (float)
SORCERESS               =   0.0 ; [Royalist] (float)
SUMMONER                =   6.0 ; [Nationalist] (float)
WARLOCK                 =  20.0 ; [Tech - All] (float)
WARMAGE                 =   4.0 ; (Magician) [Except Ceyah] (float)
WIZARD                  =   4.0 ; [Council] (float)
WRAITH                  =  10.0 ; [Ceyah] (float)
ZEALOT                  =   2.0 ; [Nationalist] (float)
;	Ahriman's Gift Support Units
DEFILER                 =   8.0	; [Tech - Ceyah] (float)
FANATIC                 =   8.0	; [Nationalist Elite Priest] (float)
INVOKER                 =   2.0 ; [Nationalist Elite Mage] (float)
KHALDUNITE_GOLEM	=   6.0 ; [Tech - All] (float)
MAELSTROM_ORB           =   6.0 ; [Except Ceyah] (float)
SHADOW_PROPHET          =  12.0 ; [Tech - Ceyah] (float)
SLAANRI_MYSTIC          =  24.0 ; [Slaanri] (float)
SLAANRI_SLAVER		=  14.0 ; [Tech - All] (float)
ORACLE			=   2.0 ;
MACABRE			=  12.0 ;
SORCEROR		=   4.0 ;
STORM_LORD		=   4.0 ;
ACOLYTE			=   0.0 ;
ELEMENTALIST		=   4.0 ;
HIGH_PRIEST		=   0.0 ;
;	LB units
CROSSBOWMAN2		=   4.0 ;
MAELSTROM_ORB2		=   8.0 ;
DREAD_KNIGHT		=  17.0 ;
ARCHER_SUPPORT		=   4.0 ;
DISCIPLEMONK		=   2.0 ;
SHADELING_SUPPORT	=   8.0 ;
TARKAN			=   2.0 ;
OVERSEER		=   2.0 ;
LICHSUPER		=  30.0 ;


[CompanySupportChoiceRatio]
support			=  0.60	; use specialty support units (mages, paladins, whatever) (float)
homogenous		=  0.10	; support unit matching the front line ones (float)
complementary		=  0.30 ;
none			=  0.00 ;

[CompanySupportPriorityBonus]
percent_big_engineer    =  0.00	; percent of engineer companies that have 6 versus only 4 engineer units (float)
matching_support	=  -8.0;
fuzziness		=  10.0;

[PoliticalTendencies]
aloof                   =   0.05	; (0.0-0.5) % push opinion towards 0 (neutral) each think turn
levelheaded		=   -0.1;
chaotic                 =   0.1 ; (0.0-0.5) random shift of opinion on each think turn. 0.5 would result in a random shift from -25% to +25%
vindictive              =   0.2 ; (0.0-0.5) For all ENEMIES, % reduction for good events & % increase of bad events
suspicious              =   0.3 ; (0.0-0.5) For all players, % reduction for good events & % increase of bad events
loyal			=   0.2 ;
greedy                  =   1.0 ; (-1.0-1.0) For all players, % increase(decrease) in opinion effects from tribute


[PoliticalTreatyOfferThreshold]
DeclareWar              =  -1.0	; If opinion falls below this point, the player will delare war
CancelAlliance		=  55.0 ;


[PoliticalTreatyAcceptThreshold]
OfferPeace		=  1.0	; Accept an offered peace treaty
OfferAlliance		=  80.0 ;


[BuildTemplates]
Template1 	= EarlyMili
Template2 	= MidMili
Template3	= EliteMili
Template4 	= EarlyEcon
Template5 	= MidEcon
Template6 	= LateEcon
Template7 	= HarounSanctuary
Template8 	= DraugaEnclave
Template9 	= GauriStronghold
Template10 	= SlaanriKraal
Template11	= RoyalMili
Template12	= MaretenMili


[EarlyMili]
Component1 	= CarpentryGuild
Component2 	= Blacksmith
Component3 	= SupplyPost
MinEconomy 	= 20		; default -infinity
OnlyFaction 	= CEYAH		; default ANY
Bonus 		= 500		; default 50


[MidMili]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3	= SupplyPost
Component4 	= Library
Component5 	= MiningPost
MinEconomy 	= 40		; default -infinity
OnlyFaction 	= CEYAH		; default ANY
Bonus 		= 500		; default 50


[EliteMili]
Component1 	= CarpentryGuild
Component2 	= ManaForge
Component3 	= Temple
Component4 	= MageCollege
Component5 	= SupplyPost
MinEconomy 	= 105		; default -infinity
OnlyFaction 	= CEYAH		; default ANY
Bonus 		= 1000		; default 50


[EarlyEcon]
Component1 	= CarpentryGuild
Component2 	= Bank
MaxInstances 	= 2		; default 1
Race 		= MARETEN	; default ANY


[MidEcon]
Component1 	= CarpentryGuild
Component2 	= Blacksmith
Component3 	= Bank
MaxInstances 	= 2		; default 1
MinEconomy 	= 60		; default -infinity
Race 		= MARETEN	; default ANY


[LateEcon]
Component1 	= CarpentryGuild
Component2 	= ManaForge
Component3 	= SupplyPost
MaxInstances 	= 2		; default 1
MinEconomy 	= 85		; default -infinity
Race 		= MARETEN	; default ANY


[HarounSanctuary]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3 	= Library
Component4	= Bank
Race 		= HAROUN	; default ANY
Bonus 		= 500		; default 50


[DraugaEnclave]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3 	= Library
Component4	= Bank
Race 		= DRAUGA	; default ANY
Bonus 		= 500		; default 50


[GauriStronghold]
Component1 	= CarpentryGuild
Component2	= Blacksmith
Component3 	= Library
Component4	= Bank
Race 		= GAURI		; default ANY
Bonus 		= 500		; default 50


[SlaanriKraal]
Component1 	= Quarry
Component2 	= Temple
Race 		= SLAAN		; default ANY
Bonus 		= 500		; default 50


[RoyalMili]
Component1	= CarpentryGuild
Component2 	= ArmoryGuild
Component3 	= Library
Component4	= Barracks
Component5	= Workshop
MinEconomy 	= 25		; default -infinity
OnlyFaction 	= ROYALIST	; default ANY
Bonus 		= 500		; default 50


[MaretenMili]
Component1	= CarpentryGuild
Component2 	= ArmoryGuild
Component3 	= Library
Component4	= Bank
MinEconomy 	= 25		; default -infinity
ExceptFaction 	= CEYAH		; default ANY
Race 		= MARETEN	; default ANY

